/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuddyMatch { 'score' : bigint, 'profile' : BuddyProfile }
export interface BuddyProfile {
  'id' : bigint,
  'bio' : string,
  'city' : string,
  'name' : string,
  'languages' : Array<string>,
  'isAvailable' : boolean,
  'professionalField' : string,
  'countryOfOrigin' : string,
}
export interface Deadline {
  'id' : bigint,
  'status' : DeadlineStatus,
  'title' : string,
  'officialLink' : string,
  'dueDate' : string,
  'description' : string,
  'stage' : Stage,
}
export type DeadlineStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'urgent' : null };
export interface FormField { 'key' : string, 'value' : string }
export interface RightsQuestion {
  'id' : bigint,
  'question' : string,
  'options' : Array<string>,
}
export interface RightsResult {
  'contactInfo' : string,
  'summary' : string,
  'legalBasis' : string,
  'violationType' : string,
}
export type Stage = { 'arrival' : null } |
  { 'professional' : null } |
  { 'settling' : null };
export interface UserProfile {
  'arrivalDate' : string,
  'city' : string,
  'profession' : string,
  'fullName' : string,
  'nationality' : string,
  'visaType' : VisaType,
  'familySituation' : string,
}
export type VisaType = { 'blueCard' : null } |
  { 'student' : null } |
  { 'generalResidence' : null };
export interface _SERVICE {
  'getBuddies' : ActorMethod<[], Array<BuddyProfile>>,
  'getDeadlines' : ActorMethod<[VisaType, string], Array<Deadline>>,
  'getPrefilledForm' : ActorMethod<[string], Array<FormField>>,
  'getRightsQuestions' : ActorMethod<[], Array<RightsQuestion>>,
  'getRightsResult' : ActorMethod<
    [Array<[bigint, string]>],
    Array<RightsResult>
  >,
  'getTopMatches' : ActorMethod<[string, string, string], Array<BuddyMatch>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];