/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BuddyProfile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'isAvailable' : IDL.Bool,
  'professionalField' : IDL.Text,
  'countryOfOrigin' : IDL.Text,
});
export const VisaType = IDL.Variant({
  'blueCard' : IDL.Null,
  'student' : IDL.Null,
  'generalResidence' : IDL.Null,
});
export const DeadlineStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'urgent' : IDL.Null,
});
export const Stage = IDL.Variant({
  'arrival' : IDL.Null,
  'professional' : IDL.Null,
  'settling' : IDL.Null,
});
export const Deadline = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeadlineStatus,
  'title' : IDL.Text,
  'officialLink' : IDL.Text,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'stage' : Stage,
});
export const FormField = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const RightsQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const RightsResult = IDL.Record({
  'contactInfo' : IDL.Text,
  'summary' : IDL.Text,
  'legalBasis' : IDL.Text,
  'violationType' : IDL.Text,
});
export const BuddyMatch = IDL.Record({
  'score' : IDL.Nat,
  'profile' : BuddyProfile,
});
export const UserProfile = IDL.Record({
  'arrivalDate' : IDL.Text,
  'city' : IDL.Text,
  'profession' : IDL.Text,
  'fullName' : IDL.Text,
  'nationality' : IDL.Text,
  'visaType' : VisaType,
  'familySituation' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBuddies' : IDL.Func([], [IDL.Vec(BuddyProfile)], ['query']),
  'getDeadlines' : IDL.Func(
      [VisaType, IDL.Text],
      [IDL.Vec(Deadline)],
      ['query'],
    ),
  'getPrefilledForm' : IDL.Func([IDL.Text], [IDL.Vec(FormField)], ['query']),
  'getRightsQuestions' : IDL.Func([], [IDL.Vec(RightsQuestion)], ['query']),
  'getRightsResult' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      [IDL.Vec(RightsResult)],
      ['query'],
    ),
  'getTopMatches' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(BuddyMatch)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BuddyProfile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'isAvailable' : IDL.Bool,
    'professionalField' : IDL.Text,
    'countryOfOrigin' : IDL.Text,
  });
  const VisaType = IDL.Variant({
    'blueCard' : IDL.Null,
    'student' : IDL.Null,
    'generalResidence' : IDL.Null,
  });
  const DeadlineStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'urgent' : IDL.Null,
  });
  const Stage = IDL.Variant({
    'arrival' : IDL.Null,
    'professional' : IDL.Null,
    'settling' : IDL.Null,
  });
  const Deadline = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeadlineStatus,
    'title' : IDL.Text,
    'officialLink' : IDL.Text,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'stage' : Stage,
  });
  const FormField = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const RightsQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const RightsResult = IDL.Record({
    'contactInfo' : IDL.Text,
    'summary' : IDL.Text,
    'legalBasis' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const BuddyMatch = IDL.Record({
    'score' : IDL.Nat,
    'profile' : BuddyProfile,
  });
  const UserProfile = IDL.Record({
    'arrivalDate' : IDL.Text,
    'city' : IDL.Text,
    'profession' : IDL.Text,
    'fullName' : IDL.Text,
    'nationality' : IDL.Text,
    'visaType' : VisaType,
    'familySituation' : IDL.Text,
  });
  
  return IDL.Service({
    'getBuddies' : IDL.Func([], [IDL.Vec(BuddyProfile)], ['query']),
    'getDeadlines' : IDL.Func(
        [VisaType, IDL.Text],
        [IDL.Vec(Deadline)],
        ['query'],
      ),
    'getPrefilledForm' : IDL.Func([IDL.Text], [IDL.Vec(FormField)], ['query']),
    'getRightsQuestions' : IDL.Func([], [IDL.Vec(RightsQuestion)], ['query']),
    'getRightsResult' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        [IDL.Vec(RightsResult)],
        ['query'],
      ),
    'getTopMatches' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(BuddyMatch)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };