/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RightsQuestion {
    id: bigint;
    question: string;
    options: Array<string>;
}
export interface RightsResult {
    contactInfo: string;
    summary: string;
    legalBasis: string;
    violationType: string;
}
export interface FormField {
    key: string;
    value: string;
}
export interface BuddyMatch {
    score: bigint;
    profile: BuddyProfile;
}
export interface Deadline {
    id: bigint;
    status: DeadlineStatus;
    title: string;
    officialLink: string;
    dueDate: string;
    description: string;
    stage: Stage;
}
export interface BuddyProfile {
    id: bigint;
    bio: string;
    city: string;
    name: string;
    languages: Array<string>;
    isAvailable: boolean;
    professionalField: string;
    countryOfOrigin: string;
}
export interface UserProfile {
    arrivalDate: string;
    city: string;
    profession: string;
    fullName: string;
    nationality: string;
    visaType: VisaType;
    familySituation: string;
}
export enum DeadlineStatus {
    upcoming = "upcoming",
    completed = "completed",
    urgent = "urgent"
}
export enum Stage {
    arrival = "arrival",
    professional = "professional",
    settling = "settling"
}
export enum VisaType {
    blueCard = "blueCard",
    student = "student",
    generalResidence = "generalResidence"
}
export interface backendInterface {
    getBuddies(): Promise<Array<BuddyProfile>>;
    getDeadlines(visaType: VisaType, arrivalDate: string): Promise<Array<Deadline>>;
    getPrefilledForm(formType: string): Promise<Array<FormField>>;
    getRightsQuestions(): Promise<Array<RightsQuestion>>;
    getRightsResult(answers: Array<[bigint, string]>): Promise<Array<RightsResult>>;
    getTopMatches(city: string, field: string, origin: string): Promise<Array<BuddyMatch>>;
    getUserProfile(): Promise<UserProfile | null>;
    saveUserProfile(profile: UserProfile): Promise<void>;
}
import type { Deadline as _Deadline, DeadlineStatus as _DeadlineStatus, Stage as _Stage, UserProfile as _UserProfile, VisaType as _VisaType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getBuddies(): Promise<Array<BuddyProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuddies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuddies();
            return result;
        }
    }
    async getDeadlines(arg0: VisaType, arg1: string): Promise<Array<Deadline>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeadlines(to_candid_VisaType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeadlines(to_candid_VisaType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrefilledForm(arg0: string): Promise<Array<FormField>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrefilledForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrefilledForm(arg0);
            return result;
        }
    }
    async getRightsQuestions(): Promise<Array<RightsQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRightsQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRightsQuestions();
            return result;
        }
    }
    async getRightsResult(arg0: Array<[bigint, string]>): Promise<Array<RightsResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRightsResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRightsResult(arg0);
            return result;
        }
    }
    async getTopMatches(arg0: string, arg1: string, arg2: string): Promise<Array<BuddyMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopMatches(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopMatches(arg0, arg1, arg2);
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(to_candid_UserProfile_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(to_candid_UserProfile_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DeadlineStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeadlineStatus): DeadlineStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Deadline_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deadline): Deadline {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Stage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stage): Stage {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_VisaType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisaType): VisaType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrivalDate: string;
    city: string;
    profession: string;
    fullName: string;
    nationality: string;
    visaType: _VisaType;
    familySituation: string;
}): {
    arrivalDate: string;
    city: string;
    profession: string;
    fullName: string;
    nationality: string;
    visaType: VisaType;
    familySituation: string;
} {
    return {
        arrivalDate: value.arrivalDate,
        city: value.city,
        profession: value.profession,
        fullName: value.fullName,
        nationality: value.nationality,
        visaType: from_candid_VisaType_n13(_uploadFile, _downloadFile, value.visaType),
        familySituation: value.familySituation
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DeadlineStatus;
    title: string;
    officialLink: string;
    dueDate: string;
    description: string;
    stage: _Stage;
}): {
    id: bigint;
    status: DeadlineStatus;
    title: string;
    officialLink: string;
    dueDate: string;
    description: string;
    stage: Stage;
} {
    return {
        id: value.id,
        status: from_candid_DeadlineStatus_n6(_uploadFile, _downloadFile, value.status),
        title: value.title,
        officialLink: value.officialLink,
        dueDate: value.dueDate,
        description: value.description,
        stage: from_candid_Stage_n8(_uploadFile, _downloadFile, value.stage)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blueCard: null;
} | {
    student: null;
} | {
    generalResidence: null;
}): VisaType {
    return "blueCard" in value ? VisaType.blueCard : "student" in value ? VisaType.student : "generalResidence" in value ? VisaType.generalResidence : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
} | {
    urgent: null;
}): DeadlineStatus {
    return "upcoming" in value ? DeadlineStatus.upcoming : "completed" in value ? DeadlineStatus.completed : "urgent" in value ? DeadlineStatus.urgent : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrival: null;
} | {
    professional: null;
} | {
    settling: null;
}): Stage {
    return "arrival" in value ? Stage.arrival : "professional" in value ? Stage.professional : "settling" in value ? Stage.settling : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deadline>): Array<Deadline> {
    return value.map((x)=>from_candid_Deadline_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_VisaType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisaType): _VisaType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arrivalDate: string;
    city: string;
    profession: string;
    fullName: string;
    nationality: string;
    visaType: VisaType;
    familySituation: string;
}): {
    arrivalDate: string;
    city: string;
    profession: string;
    fullName: string;
    nationality: string;
    visaType: _VisaType;
    familySituation: string;
} {
    return {
        arrivalDate: value.arrivalDate,
        city: value.city,
        profession: value.profession,
        fullName: value.fullName,
        nationality: value.nationality,
        visaType: to_candid_VisaType_n1(_uploadFile, _downloadFile, value.visaType),
        familySituation: value.familySituation
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisaType): {
    blueCard: null;
} | {
    student: null;
} | {
    generalResidence: null;
} {
    return value == VisaType.blueCard ? {
        blueCard: null
    } : value == VisaType.student ? {
        student: null
    } : value == VisaType.generalResidence ? {
        generalResidence: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
